services:
  app:
    image: ${DOCKER_IMAGE}
    ports:
      - "80:80"
    environment:
      - PORT=80
      - DB_PATH=/app/data/database.sqlite
      - ENVIRONMENT=production
    volumes:
      - type: bind
        source: /root/data/
        target: /app/data/
        consistency: consistent
