# This workflow will be triggered on push to develop branch (every merged PR to develop) and
# build and push the Docker image to GitHub Container Registry.
name: "Build docker image"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./itu-minitwit-golang
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get short SHA
        id: get_short_sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./itu-minitwit-golang
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/itu-minitwit-golang:${{ env.short_sha }}


